---
title: kseniazadniprana
timezone: UTC
collections:
  featured_categories:
    title: Featured Categories
    output: true
    permalink: "/:name/"
  featured_tags:
    title: Featured Tags
    output: true
    permalink: "/tag-:name/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: hyde
  values:
    accent_color: rgb(38,139,210)
    accent_image:
      background: rgb(32,32,32)
      overlay: false
- scope:
    path: ''
    type: projects
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_categories
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_tags
  values:
    seo:
      type: WebPage
url: https://domain.tld
baseurl: 
lang: en
description: "\n"
tagline: 
logo: "/assets/icons/icon.png"
author:
  name: "<firstname> <lastname>"
  email: "<mail@domain.tld>"
menu:
- title: Hydejack
  url: "/hydejack/"
- title: Hyde
  url: "/hyde/"
- title: Documentation
  url: "/docs/"
- title: About
  url: "/about/"
copyright: "© 2018. All rights reserved."
permalink: "/:categories/:year-:month-:day-:title/"
paginate: 5
paginate_path: "/blog/page-:num/"
accent_image: "/assets/img/sidebar-bg.jpg"
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)
google_fonts: Roboto+Slab:400|Noto+Sans:400,400i,700,700i
font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
hydejack:
  post_addons:
  - about
  - newsletter
  - related
  - random
  project_addons:
  - about
  - newsletter
  - other
  no_google_fonts: false
  no_mark_external: true
  no_push_state: false
  no_drawer: false
  no_img: false
  no_inline_css: false
  no_page_style: false
  no_break_layout: false
  no_structured_data: false
  no_theme_color: false
  use_lsi: false
  cookies_banner: false
  advertise: false
  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true
  offline:
    enabled: false
    cache_version: 1
exclude:
- vendor
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- package-lock.json
- webpack.config.js
- "*.gemspec"
- _js
- _plugins
- ".sass-cache"
include:
- LICENSE.md
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
  with_frontmatter: true
relative_links:
  collections: true
titles_from_headings:
  strip_title: true
  collections: true
kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
compress_html:
  comments:
  - "<!-- "
  - " -->"
  clippings: all
  endings: all
  ignore:
    envs:
    - development
sass:
  style: compressed
